const products = [
    {
      id: 1,
      name: 'Alienware M15 Gaming Laptop',
      description: 'High-performance gaming laptop with NVIDIA GeForce RTX 3070 GPU and Intel Core i7 processor, designed for hardcore gamers.',
      brand: 'Alienware',
      image: '/Images/AlienwareM15.jpg',
      price: '$2200',
      discountPrice: '$2000',
    },
    {
      id: 2,
      name: 'Apple MacBook Air M1',
      description: 'Slim and lightweight ultrabook with Apple M1 chip, offering powerful performance and long battery life.',
      brand: 'Apple',
      image: '/Images/AppleMacBookAirM1.jpg',
      price: '$1000',
      discountPrice: '$950',
    },
    {
      id: 3,
      name: 'Samsung Galaxy S21 Ultra',
      description: 'Flagship smartphone with a 108MP camera, 120Hz AMOLED display, and Exynos 2100 processor for top-tier mobile performance.',
      brand: 'Samsung',
      image: '/Images/SamsungGalaxyS21Ultra.jpg',
      price: '$1200',
      discountPrice: '$1150',
    },
    {
      id: 4,
      name: 'ASUS ROG Phone 5',
      description: 'High-refresh rate AMOLED display and Snapdragon 888 processor optimized for the best gaming experience on a smartphone.',
      brand: 'ASUS',
      image: '/Images/ASUSROGPhone5.jpg',
      price: '$999',
      discountPrice: '$950',
    },
    {
      id: 5,
      name: 'Sony PlayStation 5',
      description: 'Next-gen gaming console with immersive 4K gaming, ultra-high speed SSD, and haptic feedback controller.',
      brand: 'Sony',
      image: '/Images/SonyPlayStation5.jpg',
      price: '$499',
      discountPrice: '$450',
    },
    {
      id: 6,
      name: 'Apple AirPods Pro',
      description: 'Noise-canceling wireless earbuds with superior sound quality and transparency mode, perfect for an immersive audio experience.',
      brand: 'Apple',
      image: '/Images/AppleAirPodsPro.jpg',
      price: '$249',
      discountPrice: '$219',
    },
    {
      id: 7,
      name: 'Garmin Fenix 6 Pro Smartwatch',
      description: 'Premium smartwatch with GPS, health monitoring, and advanced sports tracking features, built for the outdoors.',
      brand: 'Garmin',
      image: '/Images/GarminFenix6ProSmartwatch.jpg',
      price: '$699',
      discountPrice: '$649',
    },
    {
      id: 8,
      name: 'Apple iPad Pro 12.9-inch',
      description: 'High-resolution screen tablet with the Apple M1 chip, offering unparalleled performance and display quality.',
      brand: 'Apple',
      image: '/Images/AppleiPadPro12.9-inch.jpg',
      price: '$1099',
      discountPrice: '$999',
    },
    {
      id: 9,
      name: 'HP Omen 30L Gaming Desktop',
      description: 'Custom-built desktop PC with NVIDIA GeForce RTX 3080 GPU and Intel Core i9 processor, optimized for gaming and productivity.',
      brand: 'HP',
      image: '/Images/HPOmen30LGamingDesktop.jpeg',
      price: '$2500',
      discountPrice: '$2300',
    },
    {
      id: 10,
      name: 'Anker PowerWave Wireless Charger',
      description: 'Fast wireless charger compatible with all Qi-enabled devices, offering reliable charging with over-voltage protection.',
      brand: 'Anker',
      image: '/Images/AnkerPowerWaveWirelessCharger.jpg',
      price: '$49',
      discountPrice: '$39',
    },
  ];
  
  export default products;
  